const views = document.querySelectorAll('.view');
const toast = document.querySelector('#toast');
const nav=document.querySelector('.nav'); const financeNav=document.createElement('button'); financeNav.dataset.view='financeiro'; financeNav.innerHTML='<span>◫</span> Financeiro'; nav.appendChild(financeNav);
const finance=document.createElement('section'); finance.id='financeiro'; finance.className='view'; finance.innerHTML='<div class="page-title"><div><span class="eyebrow">COBRANÇAS E ASSINATURAS</span><h2>Financeiro</h2></div><button class="primary" id="createCharge">+ Criar cobrança</button></div><div class="metrics"><div><span>RECEBIDO ESTE MÊS</span><strong class="green-text">R$ 3.780</strong><small>2 pagamentos confirmados</small></div><div><span>A RECEBER</span><strong class="amber">R$ 990</strong><small>1 cobrança pendente</small></div><div><span>INADIMPLENTES</span><strong>0</strong><small>nenhuma conta bloqueada</small></div><div><span>PRÓXIMA COBRANÇA</span><strong>03/03</strong><small>Paraná Refinaria</small></div></div><div class="table-card"><div class="table-head"><span>EMPRESA</span><span>PLANO</span><span>VALOR</span><span>PAGAMENTO</span></div><div class="table-row"><b>Paraná Refinaria</b><span>Profissional</span><span>R$ 1.890/mês</span><span class="status-pill green">● pago</span></div><div class="table-row"><b>Santa Cruz Siderúrgica</b><span>Profissional</span><span>R$ 1.890/mês</span><span class="status-pill green">● pago</span></div><div class="table-row"><b>Mata Energia</b><span>Essencial</span><span>R$ 990/mês</span><span><button class="status-pill amber-pill action-pay">● pendente</button></span></div></div>';
document.querySelector('.main').appendChild(finance); finance.querySelector('.eyebrow').textContent='CLIENTES · COBRANÇAS E ASSINATURAS'; finance.querySelector('h2').textContent='Financeiro por cliente'; finance.querySelector('.table-head').innerHTML='<span>CLIENTE</span><span>PLANO / ASSINATURA</span><span>VALOR</span><span>ACESSO</span>'; finance.querySelector('.table-row:last-child .action-pay').title='Cobrança da Mata Energia'; financeNav.addEventListener('click',()=>activate('financeiro')); finance.querySelector('#createCharge').onclick=()=>showToast('Cobrança vinculada ao cliente selecionado'); finance.querySelector('.action-pay').onclick=()=>showToast('Link de pagamento da Mata Energia preparado');
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function activate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>activate(el.dataset.view)));
const items=[['Verificação da pressão do manômetro principal','2,4 bar','checked'],['Análise de vazamento em válvula V-204','negativo','checked'],['Teste de continuidade no painel de comando','atenção','attention'],['Registro fotográfico das condições gerais','0 fotos anexadas','checked'],['Calibração do sensor de temperatura ST-07','pendente','']];
const list=document.querySelector('#checklist'); list.innerHTML=items.map((x,i)=>`<div class="check-item" data-index="${i}"><span class="check ${x[2]}">${x[2]==='checked'?'✓':x[2]==='attention'?'!':''}</span><span>${x[0]}</span><small>${x[1]}</small></div>`).join('');
const checklistHeading=document.querySelector('.checklist-card h2');const categoryButton=document.createElement('button');categoryButton.type='button';categoryButton.className='inline-action';categoryButton.textContent='+ Nova categoria';checklistHeading.append(' ',categoryButton);categoryButton.onclick=()=>{const category=prompt('Nome da categoria (ex.: Sistema de detecção e alarme)');if(!category?.trim())return;const raw=prompt('Itens da categoria, um por linha:');if(!raw?.trim())return;const newItems=raw.split(/\r?\n/).map(item=>item.trim()).filter(Boolean);const categories=JSON.parse(localStorage.getItem('vt_checklist_categories')||'[]');categories.push({name:category.trim(),items:newItems});localStorage.setItem('vt_checklist_categories',JSON.stringify(categories));const heading=document.createElement('div');heading.className='check-category';heading.textContent=category.trim();list.appendChild(heading);newItems.forEach(item=>{const row=document.createElement('div');row.className='check-item';row.innerHTML='<span class="check"></span><span></span><small>pendente</small>';row.querySelector('span:nth-child(2)').textContent=item;list.appendChild(row)});showToast(`${newItems.length} item(ns) adicionados à categoria`)};
JSON.parse(localStorage.getItem('vt_checklist_categories')||'[]').forEach(category=>{const heading=document.createElement('div');heading.className='check-category';heading.textContent=category.name;list.appendChild(heading);category.items.forEach(item=>{const row=document.createElement('div');row.className='check-item';row.innerHTML='<span class="check"></span><span></span><small>pendente</small>';row.querySelector('span:nth-child(2)').textContent=item;list.appendChild(row)})});
list.addEventListener('click',e=>{const row=e.target.closest('.check-item');if(!row)return;const box=row.querySelector('.check');box.classList.toggle('checked');box.textContent=box.classList.contains('checked')?'✓':'';showToast('Item atualizado no checklist')});
const makeEvidenceInput=(capture)=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=!capture;if(capture)input.setAttribute('capture','environment');input.hidden=true;input.tabIndex=-1;input.setAttribute('aria-label',capture?'Tirar foto com a câmera':'Escolher fotos da galeria');document.body.appendChild(input);return input};
const cameraInput=makeEvidenceInput(true);const galleryInput=makeEvidenceInput(false);const savedEvidence=(()=>{try{const value=JSON.parse(localStorage.getItem('vt_evidence')||'[]');return Array.isArray(value)?value.slice(0,4):[]}catch{return []}})();const photos=[...document.querySelectorAll('.photo')];
function updateEvidenceCount(){const label=list.querySelector('.check-item[data-index="3"] small');if(!label)return;const count=savedEvidence.filter(Boolean).length;label.textContent=count===1?'1 foto anexada':`${count} fotos anexadas`}
function paintEvidence(src,index){if(!photos[index])return;photos[index].style.backgroundImage=`linear-gradient(#0002,#0002),url("${src}")`;photos[index].style.backgroundSize='cover';photos[index].style.backgroundPosition='center';photos[index].classList.add('has-photo');const label=photos[index].querySelector('small');if(label)label.textContent=`FOTO ${index+1}`}
function compressEvidence(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/')){reject(new Error('O arquivo selecionado não é uma imagem.'));return}const url=URL.createObjectURL(file);const image=new Image();image.onload=()=>{try{const limit=1600,scale=Math.min(1,limit/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d');if(!context)throw new Error('Não foi possível preparar a imagem.');context.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))}catch(error){reject(error)}finally{URL.revokeObjectURL(url)}};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível abrir esta foto. Tente outra imagem.'))};image.src=url})}
async function addEvidence(fileList){const files=[...fileList];if(!files.length)return;const freeSlots=photos.map((_,index)=>index).filter(index=>!savedEvidence[index]);const selected=files.slice(0,freeSlots.length);if(!selected.length){showToast('Limite de 4 fotos atingido.');return}let added=0;for(let i=0;i<selected.length;i++){try{const data=await compressEvidence(selected[i]);const slot=freeSlots[i];const next=savedEvidence.slice();next[slot]=data;try{localStorage.setItem('vt_evidence',JSON.stringify(next))}catch{showToast('Armazenamento do celular cheio. Libere espaço ou escolha fotos menores.');break}savedEvidence[slot]=data;paintEvidence(data,slot);updateEvidenceCount();added++}catch(error){showToast(error.message||'Não foi possível anexar a foto.');break}}if(added)showToast(`${added} foto(s) adicionada(s)`);if(files.length>selected.length)showToast('Limite de 4 fotos; parte da seleção não foi adicionada.')}
savedEvidence.forEach((src,i)=>paintEvidence(src,i));updateEvidenceCount();document.querySelector('#takePhoto').addEventListener('click',()=>cameraInput.click());document.querySelector('#choosePhotos').addEventListener('click',()=>galleryInput.click());cameraInput.addEventListener('change',()=>{addEvidence(cameraInput.files);cameraInput.value=''});galleryInput.addEventListener('change',()=>{addEvidence(galleryInput.files);galleryInput.value=''});document.querySelector('.photos').addEventListener('click',event=>{if(event.target.closest('.photo'))galleryInput.click()});
async function downloadReport(){
  const title=document.querySelector('.topbar h1')?.textContent.replace(/ATUALIZADO.*$/,'').trim();
  const order=document.querySelector('.topbar .eyebrow')?.textContent.trim()||'ORDEM DE SERVIÇO';
  const status=document.querySelector('.topbar .status-pill')?.textContent.replace(/^●\s*/,'').trim()||'não informado';
  const responsible=document.querySelector('.assignee b')?.textContent.trim()||'não informado';
  const client=document.querySelector('.client-row b')?.textContent.trim()||'Cliente não informado';
  const checklist=[...document.querySelectorAll('#checklist .check-item')].map(row=>{const parts=row.querySelectorAll('span,small');return `${parts[1]?.textContent.trim()||''}: ${parts[2]?.textContent.trim()||''}`});
  const labels=[...document.querySelectorAll('.photo small')].map(item=>item.textContent.trim()).filter(Boolean);
  const photos=savedEvidence.filter(Boolean);
  if(!title||checklist.length===0){showToast('Aguarde o carregamento dos dados antes de exportar');return}
  const cp1252={8364:128,8218:130,402:131,8222:132,8230:133,8224:134,8225:135,710:136,8240:137,352:138,8249:139,338:140,381:142,8216:145,8217:146,8220:147,8221:148,8226:149,8211:150,8212:151,732:152,8482:153,353:154,8250:155,339:156,382:158,376:159};
  const pdfText=value=>`<${[...String(value)].map(char=>{const code=char.codePointAt(0);return (cp1252[code]??(code<=255?code:63)).toString(16).padStart(2,'0')}).join('')}>`;
  const newline=String.fromCharCode(10);const encoder=new TextEncoder();const size=value=>encoder.encode(value).length;
  const footer='ECOSAFETY ENGENHARIA DE INCÊNDIO  |  Relatório técnico gerado pelo sistema';
  const textBlock=(lines,x=42,y=780,leading=18,font=10)=>['BT',`/F1 ${font} Tf`,`${x} ${y} Td`,...lines.flatMap((line,i)=>[i?'0 -'+leading+' Td':'',`${pdfText(line)} Tj`]).filter(Boolean),'ET'].join(newline);
  const cover=textBlock(['ECOSAFETY','TECNOLOGIA E ENGENHARIA DE INCÊNDIO','','O.S. Nº 4744',client,title,'',order,'Período: '+new Date().toLocaleDateString('pt-BR')],118,760,38,18);
  const technical=textBlock(['SISTEMA DE VISTORIA E INSPEÇÃO',`${order} - ${title}`,'','CLIENTE',client,'STATUS',status,'RESPONSÁVEL',responsible,'','CHECKLIST DE INSPEÇÃO',...checklist.map((line,i)=>`${i+1}. ${line}`),'','ASSINATURA DO RESPONSÁVEL','Nome: '+responsible,'Função: Técnico de manutenção','Assinatura: ______________________________','Local e data: '+client+', '+new Date().toLocaleDateString('pt-BR')],42,790,17,10);
  const photoHeading=textBlock(['EVIDÊNCIA FOTOGRÁFICA',`${order} - ${title}`,'','Fotos anexadas: '+photos.length],42,790,18,15);
  const imageData=await Promise.all(photos.map(src=>new Promise(resolve=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=800;canvas.height=600;canvas.getContext('2d').drawImage(image,0,0,800,600);const raw=atob(canvas.toDataURL('image/jpeg',.86).split(',')[1]);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);resolve({bytes,width:800,height:600})};image.onerror=()=>resolve(null);image.src=src})));
  const validImages=imageData.filter(Boolean);if(validImages.length!==photos.length){showToast('Não foi possível processar uma das fotos. Anexe novamente e tente exportar.');return}const font=9,imageStart=10,photoRefs=validImages.map((_,i)=>imageStart+i);const resources=validImages.length?`/XObject << ${photoRefs.map((ref,i)=>`/Im${i+1} ${ref} 0 R`).join(' ')} >> `:'';const photoOps=validImages.length?validImages.map((_,i)=>`q 250 0 0 180 ${42+(i%2)*270} ${500-Math.floor(i/2)*205} cm /Im${i+1} Do Q`).join(newline):`BT /F1 12 Tf 42 690 Td ${pdfText('Nenhuma foto foi anexada a esta vistoria.')} Tj ET`;
  const photoCaptions=validImages.map((_,i)=>textBlock([labels[i]||`FOTO ${i+1}`],50+(i%2)*270,490-Math.floor(i/2)*205,14,8)).join(newline);
  const pageStreams=[cover+newline+textBlock([footer],42,30,0,7),technical+newline+textBlock([footer],42,30,0,7),photoHeading+newline+photoOps+newline+photoCaptions+newline+textBlock([footer],42,30,0,7)];
  const pageRefs=[3,5,7],contentRefs=[4,6,8],pageCount=3;
  const objects=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [${pageRefs.map(ref=>`${ref} 0 R`).join(' ')}] /Count ${pageCount} >>`,...pageRefs.flatMap((ref,i)=>[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> ${i===2?resources:''}>> /Contents ${contentRefs[i]} 0 R >>`,`<< /Length ${size(pageStreams[i])} >>${newline}stream${newline}${pageStreams[i]}${newline}endstream`]),`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`,...validImages.map(image=>`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.bytes.length} >>${newline}stream` )];
  const chunks=[];let pdfLength=0;const addText=(value)=>{const bytes=encoder.encode(value);chunks.push(bytes);pdfLength+=bytes.length};const addBytes=(bytes)=>{chunks.push(bytes);pdfLength+=bytes.length};addText(`%PDF-1.4${newline}`);const offsets=[0];for(let i=0;i<objects.length;i++){offsets[i+1]=pdfLength;const object=objects[i];addText(`${i+1} 0 obj${newline}`);if(i>=imageStart-1){addText(object+newline);addBytes(validImages[i-(imageStart-1)].bytes);addText(`${newline}endstream${newline}endobj${newline}`)}else addText(object+`${newline}endobj${newline}`)};const xref=pdfLength;addText(`xref${newline}0 ${objects.length+1}${newline}0000000000 65535 f ${newline}`);for(let i=1;i<offsets.length;i++)addText(`${String(offsets[i]).padStart(10,'0')} 00000 n ${newline}`);addText(`trailer${newline}<< /Size ${objects.length+1} /Root 1 0 R >>${newline}startxref${newline}${xref}${newline}%%EOF`);const finalBytes=new Uint8Array(pdfLength);let cursor=0;chunks.forEach(chunk=>{finalBytes.set(chunk,cursor);cursor+=chunk.length});const url=URL.createObjectURL(new Blob([finalBytes],{type:'application/pdf'}));const link=document.createElement('a');link.href=url;link.download='laudo-OS-2024-0187.pdf';link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);showToast(photos.length?'Laudo PDF baixado com fotos':'Laudo PDF baixado sem fotos anexadas');
}
document.querySelector('#download').onclick=downloadReport;document.querySelector('#laudos .primary').onclick=downloadReport;document.querySelector('#register').onclick=()=>showToast('Item registrado com sucesso');document.querySelector('#newClient').onclick=()=>showToast('Formulário de novo cliente aberto');document.querySelector('#invite').onclick=()=>showToast('Convite de usuário preparado');
const storedUsers=JSON.parse(localStorage.getItem('vt_users')||'[]'); const storedCompanies=JSON.parse(localStorage.getItem('vt_companies')||'[]');
function renderStored(){storedUsers.forEach(addUserCard); storedCompanies.forEach(addCompanyRow)}
function addUserCard(user){const card=document.createElement('div');card.className='card team';card.innerHTML=`<span class="avatar blue">${user.initials}</span><b>${user.name}</b><small>${user.role} · convite pendente</small>`;document.querySelector('.team-grid').appendChild(card)}
function addCompanyRow(company){const table=document.querySelector('#clientes .table-card');if(!table)return;const row=document.createElement('div');row.className='table-row client-record';row.dataset.clientId=company.id||Date.now();const price=company.price||990;const initials=(company.name||'CL').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const logo=company.logo?`<img class="client-logo" src="${company.logo}" alt="Logo de ${company.name}">`:`<span class="avatar dark">${initials}</span>`;row.innerHTML=`<span class="client-identity">${logo}<b>${company.name}</b></span><span>${company.contract||'Sem contrato'}</span><span>0</span><span class="client-status"><span class="status-pill amber-pill">● trial</span><button class="icon-action edit-client" type="button" title="Editar cliente">✎</button><button class="icon-action delete-client" type="button" title="Excluir cliente">×</button></span>`;table.appendChild(row);row.querySelector('.edit-client').onclick=()=>openModal('client',company);row.querySelector('.delete-client').onclick=()=>{if(!confirm(`Excluir o cliente ${company.name}?`))return;const index=storedCompanies.indexOf(company);if(index>=0)storedCompanies.splice(index,1);localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));row.remove();showToast('Cliente excluído')};if(company.logo)row.querySelector('.client-logo').title='Logo cadastrada'}
document.querySelector('#newCompany').onclick=()=>openModal('company');
const modal=document.querySelector('#modal'); const modalTitle=document.querySelector('#modalTitle'); const modalKicker=document.querySelector('#modalKicker'); const modalExtraLabel=document.querySelector('#modalExtraLabel');
const roleField=document.createElement('label'); roleField.innerHTML='Perfil de acesso<select id="modalRole"><option>Administrador</option><option selected>Técnico de campo</option><option>Supervisor</option><option>Visualizador</option></select>'; document.querySelector('#modalForm').insertBefore(roleField,document.querySelector('#modalForm button'));
const accountFields=document.createElement('div'); accountFields.innerHTML='<label>E-mail de acesso<input id="accountEmail" type="email" placeholder="admin@empresa.com"></label><label>Senha inicial<input id="accountPassword" type="password" minlength="6" placeholder="Mínimo de 6 caracteres"></label><label>Plano<select id="accountPlan"><option value="Essencial">Essencial</option><option value="Profissional">Profissional</option><option value="Personalizado">Personalizado</option></select></label><label>Valor mensal (R$)<input id="accountPrice" type="number" min="0" step="0.01" value="990" placeholder="Ex.: 1490"></label>'; accountFields.style.display='grid'; accountFields.style.gap='16px'; document.querySelector('#modalForm').insertBefore(accountFields,document.querySelector('#modalForm button'));
const logoField=document.createElement('label');logoField.innerHTML='Logo do cliente<input id="clientLogo" type="file" accept="image/png,image/jpeg,image/webp"><small class="field-help">PNG ou JPG, usada no cadastro e nos relatórios.</small>';document.querySelector('#modalForm').insertBefore(logoField,document.querySelector('#modalForm button'));
function openModal(type,client=null){modalTitle.textContent=type==='client'?(client?'Editar cliente':'Novo cliente'):type==='company'?'Nova empresa':'Convidar usuário';modalKicker.textContent=type==='client'?'CLIENTE + CONTA DE ACESSO':type==='company'?'NOVA CONTA SaaS':'ACESSO DA EQUIPE';modalExtraLabel.childNodes[0].textContent=type==='client'?'Contrato':type==='company'?'E-mail do responsável':'E-mail';document.querySelector('#modalExtra').placeholder=type==='client'?'Código do contrato':'responsavel@empresa.com';roleField.hidden=type!=='invite';accountFields.hidden=type!=='client';logoField.hidden=type!=='client';modal.dataset.type=type;modal.dataset.editingId=client?.id||'';if(client){document.querySelector('#modalName').value=client.name||'';document.querySelector('#modalExtra').value=client.contract||'';document.querySelector('#accountPlan').value=client.plan||'Essencial';document.querySelector('#accountPrice').value=client.price||990}else{document.querySelector('#modalName').value='';document.querySelector('#modalExtra').value=''}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelector('#modalName').focus()}
document.querySelector('#newClient').onclick=()=>openModal('client');document.querySelector('#invite').onclick=()=>openModal('invite');document.querySelector('#closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.querySelector('#modalForm').onsubmit=async e=>{e.preventDefault();const type=modal.dataset.type;const name=document.querySelector('#modalName').value;const logoFile=document.querySelector('#clientLogo').files[0];const save=logo=>{if(type==='client'){const email=document.querySelector('#accountEmail').value;const data={id:modal.dataset.editingId||Date.now(),name,email,plan:document.querySelector('#accountPlan').value,price:Number(document.querySelector('#accountPrice').value||990),contract:document.querySelector('#modalExtra').value,logo};const existing=storedCompanies.findIndex(item=>String(item.id)===String(data.id));if(existing>=0){storedCompanies[existing]=data;document.querySelector(`#clientes .client-record[data-client-id="${data.id}"]`)?.remove()}else{storedCompanies.push(data)}localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));addCompanyRow(data);showToast(existing>=0?'Cliente atualizado':'Cliente criado com logo')}else if(type==='invite'){const role=document.querySelector('#modalRole').value;const user={name,role,initials:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()};storedUsers.push(user);localStorage.setItem('vt_users',JSON.stringify(storedUsers));addUserCard(user)}else{const company={name,email:document.querySelector('#modalExtra').value};storedCompanies.push(company);localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));showToast('Empresa salva')}modal.classList.remove('open');e.target.reset()};if(type==='client'&&logoFile){const reader=new FileReader();reader.onload=()=>save(reader.result);reader.readAsDataURL(logoFile)}else save(null)};renderStored();
document.querySelector('#modalForm').addEventListener('submit',()=>{if(modal.dataset.type==='client'){const last=storedCompanies[storedCompanies.length-1];if(last){last.price=Number(document.querySelector('#accountPrice').value||990);last.plan=document.querySelector('#accountPlan').value;localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));}}if(modal.dataset.type==='order'){const order={client:document.querySelector('#orderClient').value,title:document.querySelector('#orderTitle').value,assignee:document.querySelector('#orderAssignee').value,priority:document.querySelector('#orderPriority').value,items:document.querySelector('#orderItems').value};const orders=JSON.parse(localStorage.getItem('vt_orders')||'[]');orders.push(order);localStorage.setItem('vt_orders',JSON.stringify(orders));showToast('O.S. criada e pronta para trabalho')}});
const orderFields=document.createElement('div'); orderFields.innerHTML='<label>Cliente<select id="orderClient"><option>Paraná Refinaria</option><option>Santa Cruz Siderúrgica</option><option>Mata Energia</option></select></label><label>Título da ordem<input id="orderTitle" placeholder="Ex.: Inspeção preventiva de EPI" required></label><label>Responsável<input id="orderAssignee" placeholder="Nome do técnico"></label><label>Prioridade<select id="orderPriority"><option>Normal</option><option>Alta</option><option>Urgente</option></select></label><label>Itens do checklist<textarea id="orderItems" rows="4" placeholder="Um item por linha"></textarea></label>'; orderFields.style.display='grid'; orderFields.style.gap='16px'; document.querySelector('#modalForm').insertBefore(orderFields,document.querySelector('#modalForm button')); orderFields.hidden=true;
document.querySelector('#newOrder').addEventListener('click',()=>{logoField.hidden=true;accountFields.hidden=true;roleField.hidden=true;modalExtraLabel.hidden=true});document.querySelector('#newClient').addEventListener('click',()=>{orderFields.hidden=true;modalExtraLabel.hidden=false;logoField.hidden=false});document.querySelector('#invite').addEventListener('click',()=>{orderFields.hidden=true;modalExtraLabel.hidden=false;logoField.hidden=true});
document.querySelector('#newOrder').onclick=()=>{orderFields.hidden=false;accountFields.hidden=true;roleField.hidden=true;modalExtraLabel.hidden=true;modalTitle.textContent='Nova ordem de serviço';modalKicker.textContent='ORDEM DE SERVIÇO';modal.dataset.type='order';modal.classList.add('open');document.querySelector('#modalName').focus()}; const editBtn=document.createElement('button'); editBtn.className='primary'; editBtn.textContent='Editar O.S.'; document.querySelector('.header-actions').insertBefore(editBtn,document.querySelector('#download')); editBtn.onclick=()=>{document.querySelector('#newOrder').click();modalTitle.textContent='Editar ordem de serviço';const current=JSON.parse(localStorage.getItem('vt_current_order')||'null');if(current){document.querySelector('#orderClient').value=current.client||'Paraná Refinaria';document.querySelector('#orderTitle').value=current.title||'Inspeção de EPI — Turno B';document.querySelector('#orderAssignee').value=current.assignee||'Rafael Tavares';document.querySelector('#orderPriority').value=current.priority||'Normal';document.querySelector('#orderItems').value=current.items||''}}; document.querySelector('#modalForm').addEventListener('submit',()=>{if(modal.dataset.type==='order'){const order={client:document.querySelector('#orderClient').value,title:document.querySelector('#orderTitle').value,assignee:document.querySelector('#orderAssignee').value,priority:document.querySelector('#orderPriority').value,items:document.querySelector('#orderItems').value};localStorage.setItem('vt_current_order',JSON.stringify(order));showToast('O.S. salva com sucesso')}});
const categoryDialog=document.createElement('div');categoryDialog.className='category-dialog';categoryDialog.innerHTML='<div class="category-dialog-box"><button type="button" class="modal-close category-close">×</button><span class="eyebrow">CHECKLIST</span><h3>Nova categoria de verificação</h3><label>Nome da categoria<input id="categoryName" placeholder="Ex.: Sistema de detecção e alarme"></label><label>Itens a verificar<small>Digite um item por linha</small><textarea id="categoryItems" rows="6" placeholder="Ex.: Verificar painel de alarme&#10;Testar acionadores manuais&#10;Conferir sirenes"></textarea></label><div class="category-dialog-actions"><button type="button" class="secondary category-cancel">Cancelar</button><button type="button" class="primary category-save">Adicionar ao checklist</button></div></div>';document.body.appendChild(categoryDialog);const closeCategoryDialog=()=>categoryDialog.classList.remove('open');categoryDialog.querySelector('.category-close').onclick=closeCategoryDialog;categoryDialog.querySelector('.category-cancel').onclick=closeCategoryDialog;categoryDialog.onclick=e=>{if(e.target===categoryDialog)closeCategoryDialog()};categoryDialog.querySelector('.category-save').onclick=()=>{const category=categoryDialog.querySelector('#categoryName').value.trim();const newItems=categoryDialog.querySelector('#categoryItems').value.split(/\r?\n/).map(item=>item.trim()).filter(Boolean);if(!category||!newItems.length){showToast('Informe a categoria e pelo menos um item');return}const categories=JSON.parse(localStorage.getItem('vt_checklist_categories')||'[]');categories.push({name:category,items:newItems});localStorage.setItem('vt_checklist_categories',JSON.stringify(categories));const heading=document.createElement('div');heading.className='check-category';heading.textContent=category;list.appendChild(heading);newItems.forEach(item=>{const row=document.createElement('div');row.className='check-item';row.innerHTML='<span class="check"></span><span></span><small>pendente</small>';row.querySelector('span:nth-child(2)').textContent=item;list.appendChild(row)});categoryDialog.querySelector('#categoryName').value='';categoryDialog.querySelector('#categoryItems').value='';closeCategoryDialog();showToast(`${newItems.length} item(ns) adicionados à categoria`)};categoryButton.onclick=()=>categoryDialog.classList.add('open');
