const views = document.querySelectorAll('.view');
const toast = document.querySelector('#toast');
const nav=document.querySelector('.nav'); const financeNav=document.createElement('button'); financeNav.dataset.view='financeiro'; financeNav.innerHTML='<span>◫</span> Financeiro'; nav.appendChild(financeNav);
const finance=document.createElement('section'); finance.id='financeiro'; finance.className='view'; finance.innerHTML='<div class="page-title"><div><span class="eyebrow">COBRANÇAS E ASSINATURAS</span><h2>Financeiro</h2></div><button class="primary" id="createCharge">+ Criar cobrança</button></div><div class="metrics"><div><span>RECEBIDO ESTE MÊS</span><strong class="green-text">R$ 3.780</strong><small>2 pagamentos confirmados</small></div><div><span>A RECEBER</span><strong class="amber">R$ 990</strong><small>1 cobrança pendente</small></div><div><span>INADIMPLENTES</span><strong>0</strong><small>nenhuma conta bloqueada</small></div><div><span>PRÓXIMA COBRANÇA</span><strong>03/03</strong><small>Paraná Refinaria</small></div></div><div class="table-card"><div class="table-head"><span>EMPRESA</span><span>PLANO</span><span>VALOR</span><span>PAGAMENTO</span></div><div class="table-row"><b>Paraná Refinaria</b><span>Profissional</span><span>R$ 1.890/mês</span><span class="status-pill green">● pago</span></div><div class="table-row"><b>Santa Cruz Siderúrgica</b><span>Profissional</span><span>R$ 1.890/mês</span><span class="status-pill green">● pago</span></div><div class="table-row"><b>Mata Energia</b><span>Essencial</span><span>R$ 990/mês</span><span><button class="status-pill amber-pill action-pay">● pendente</button></span></div></div>';
document.querySelector('.main').appendChild(finance); finance.querySelector('.eyebrow').textContent='CLIENTES · COBRANÇAS E ASSINATURAS'; finance.querySelector('h2').textContent='Financeiro por cliente'; finance.querySelector('.table-head').innerHTML='<span>CLIENTE</span><span>PLANO / ASSINATURA</span><span>VALOR</span><span>ACESSO</span>'; finance.querySelector('.table-row:last-child .action-pay').title='Cobrança da Mata Energia'; financeNav.addEventListener('click',()=>activate('financeiro')); finance.querySelector('#createCharge').onclick=()=>showToast('Cobrança vinculada ao cliente selecionado'); finance.querySelector('.action-pay').onclick=()=>showToast('Link de pagamento da Mata Energia preparado');
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function activate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>activate(el.dataset.view)));
const items=[['Verificação da pressão do manômetro principal','2,4 bar','checked'],['Análise de vazamento em válvula V-204','negativo','checked'],['Teste de continuidade no painel de comando','atenção','attention'],['Registro fotográfico das condições gerais','4 fotos','checked'],['Calibração do sensor de temperatura ST-07','pendente','']];
const list=document.querySelector('#checklist'); list.innerHTML=items.map((x,i)=>`<div class="check-item" data-index="${i}"><span class="check ${x[2]}">${x[2]==='checked'?'✓':x[2]==='attention'?'!':''}</span><span>${x[0]}</span><small>${x[1]}</small></div>`).join('');
list.addEventListener('click',e=>{const row=e.target.closest('.check-item');if(!row)return;const box=row.querySelector('.check');box.classList.toggle('checked');box.textContent=box.classList.contains('checked')?'✓':'';showToast('Item atualizado no checklist')});
const evidenceInput=document.createElement('input'); evidenceInput.type='file'; evidenceInput.accept='image/*'; evidenceInput.multiple=true; evidenceInput.hidden=true; document.body.appendChild(evidenceInput);
const savedEvidence=JSON.parse(localStorage.getItem('vt_evidence')||'[]'); const photos=[...document.querySelectorAll('.photo')];
function paintEvidence(src,index){if(!photos[index])return;photos[index].style.backgroundImage=`linear-gradient(#0002,#0002),url("${src}")`;photos[index].style.backgroundSize='cover';photos[index].style.backgroundPosition='center';const label=photos[index].querySelector('small');if(label)label.textContent='FOTO ANEXADA'}
savedEvidence.forEach((src,i)=>paintEvidence(src,i)); document.querySelector('.photos').style.cursor='pointer'; document.querySelector('.photos').title='Clique para anexar fotos'; document.querySelector('.photos').onclick=()=>evidenceInput.click(); evidenceInput.onchange=()=>{const files=[...evidenceInput.files].slice(0,4);files.forEach((file,index)=>{const reader=new FileReader();reader.onload=()=>{savedEvidence[index]=reader.result;paintEvidence(reader.result,index);localStorage.setItem('vt_evidence',JSON.stringify(savedEvidence));showToast(`${files.length} evidência(s) anexada(s)`) };reader.readAsDataURL(file)});evidenceInput.value=''};
document.querySelector('#download').onclick=()=>showToast('Laudo preparado para download');document.querySelector('#register').onclick=()=>showToast('Item registrado com sucesso');document.querySelector('#newClient').onclick=()=>showToast('Formulário de novo cliente aberto');document.querySelector('#invite').onclick=()=>showToast('Convite de usuário preparado');
const storedUsers=JSON.parse(localStorage.getItem('vt_users')||'[]'); const storedCompanies=JSON.parse(localStorage.getItem('vt_companies')||'[]');
function renderStored(){storedUsers.forEach(addUserCard); storedCompanies.forEach(addCompanyRow)}
function addUserCard(user){const card=document.createElement('div');card.className='card team';card.innerHTML=`<span class="avatar blue">${user.initials}</span><b>${user.name}</b><small>${user.role} · convite pendente</small>`;document.querySelector('.team-grid').appendChild(card)}
function addCompanyRow(company){const table=document.querySelector('#plataforma .table-card');const row=document.createElement('div');row.className='table-row';const price=company.price||990;row.innerHTML=`<b>${company.name}</b><span>${company.plan||'Essencial'} · R$ ${Number(price).toLocaleString('pt-BR',{minimumFractionDigits:2})}/mês</span><span>0</span><span class="status-pill amber-pill">● trial</span>`;table.appendChild(row)}
document.querySelector('#newCompany').onclick=()=>openModal('company');
const modal=document.querySelector('#modal'); const modalTitle=document.querySelector('#modalTitle'); const modalKicker=document.querySelector('#modalKicker'); const modalExtraLabel=document.querySelector('#modalExtraLabel');
const roleField=document.createElement('label'); roleField.innerHTML='Perfil de acesso<select id="modalRole"><option>Administrador</option><option selected>Técnico de campo</option><option>Supervisor</option><option>Visualizador</option></select>'; document.querySelector('#modalForm').insertBefore(roleField,document.querySelector('#modalForm button'));
const accountFields=document.createElement('div'); accountFields.innerHTML='<label>E-mail de acesso<input id="accountEmail" type="email" placeholder="admin@empresa.com"></label><label>Senha inicial<input id="accountPassword" type="password" minlength="6" placeholder="Mínimo de 6 caracteres"></label><label>Plano<select id="accountPlan"><option value="Essencial">Essencial</option><option value="Profissional">Profissional</option><option value="Personalizado">Personalizado</option></select></label><label>Valor mensal (R$)<input id="accountPrice" type="number" min="0" step="0.01" value="990" placeholder="Ex.: 1490"></label>'; accountFields.style.display='grid'; accountFields.style.gap='16px'; document.querySelector('#modalForm').insertBefore(accountFields,document.querySelector('#modalForm button'));
function openModal(type){modalTitle.textContent=type==='client'?'Novo cliente':type==='company'?'Nova empresa':'Convidar usuário';modalKicker.textContent=type==='client'?'CLIENTE + CONTA DE ACESSO':type==='company'?'NOVA CONTA SaaS':'ACESSO DA EQUIPE';modalExtraLabel.childNodes[0].textContent=type==='client'?'Contrato':type==='company'?'E-mail do responsável':'E-mail';document.querySelector('#modalExtra').placeholder=type==='client'?'Código do contrato':'responsavel@empresa.com';roleField.hidden=type!=='invite';accountFields.hidden=type!=='client';modal.dataset.type=type;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelector('#modalName').focus()}
document.querySelector('#newClient').onclick=()=>openModal('client');document.querySelector('#invite').onclick=()=>openModal('invite');document.querySelector('#closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();const type=modal.dataset.type;const name=document.querySelector('#modalName').value;if(type==='invite'){const role=document.querySelector('#modalRole').value;const user={name,role,initials:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()};storedUsers.push(user);localStorage.setItem('vt_users',JSON.stringify(storedUsers));addUserCard(user)}if(type==='company'){const company={name,email:document.querySelector('#modalExtra').value};storedCompanies.push(company);localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));addCompanyRow(company)}if(type==='client'){const email=document.querySelector('#accountEmail').value;const plan=document.querySelector('#accountPlan').value;const client={name,email,plan,contract:document.querySelector('#modalExtra').value};storedCompanies.push(client);localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));addCompanyRow(client);const user={name:`${name} · administrador`,role:'Administrador da empresa',initials:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()};storedUsers.push(user);localStorage.setItem('vt_users',JSON.stringify(storedUsers));addUserCard(user);showToast('Cliente criado com acesso e cobrança em trial')}else{showToast((type==='company'?'Empresa':'Convite')+' salvo com sucesso')}modal.classList.remove('open');e.target.reset()};renderStored();
document.querySelector('#modalForm').addEventListener('submit',()=>{if(modal.dataset.type==='client'){const last=storedCompanies[storedCompanies.length-1];if(last){last.price=Number(document.querySelector('#accountPrice').value||990);last.plan=document.querySelector('#accountPlan').value;localStorage.setItem('vt_companies',JSON.stringify(storedCompanies));}}});
